export const PENDING_GET_LIST_MOVIE = 'PENDING_GET_LIST_MOVIE';
export const GET_LIST_MOVIE_FAILED = 'GET_LIST_MOVIE_FAILED';
export const GET_LIST_MOVIE_SUCCESSFULLY = 'GET_LIST_MOVIE_SUCCESSFULLY';
