export const PENDING_GET_LIST_MOVIE = 'PENDING_GET_LIST_MOVIE';
export const GET_LIST_MOVIE_FAILED = 'GET_LIST_MOVIE_FAILED';
export const GET_LIST_MOVIE_SUCCESSFULLY = 'GET_LIST_MOVIE_SUCCESSFULLY';

export const PENDING_GET_MOVIE_BY_ID = 'PENDING_GET_MOVIE_BY_ID';
export const GET_MOVIE_BY_ID_SUCCESSFULLY = 'GET_MOVIE_BY_ID_SUCCESSFULLY';
export const GET_MOVIE_BY_ID_FAILED = 'GET_MOVIE_BY_ID_FAILED';
