export const PENDING_GET_COMMENT_CURRENT_USER =
    'PENDING_GET_COMMENT_CURRENT_USER';
export const GET_COMMENT_CURRENT_USER_SUCCESSFULLY =
    'GET_COMMENT_CURRENT_USER_SUCCESSFULLY';
export const GET_COMMENT_CURRENT_USER_FAILED =
    'GET_COMMENT_CURRENT_USER_FAILED';

export const PENDING_ADD_COMMENT = 'PENDING_ADD_COMMENT';
export const ADD_COMMENT_SUCCESSFULLY = 'ADD_COMMENT_SUCCESSFULLY';
export const ADD_COMMENT_FAILED = 'ADD_COMMENT_FAILED';

export const PENDING_GET_LIST_COMMENT = 'PENDING_GET_LIST_COMMENT';
export const GET_LIST_COMMENT_SUCCESSFULLY = 'GET_LIST_COMMENT_SUCCESSFULLY';
export const GET_LIST_COMMENT_FAILED = 'GET_LIST_COMMENT_FAILED';
