export const PENDING_GET_TYPE_MOVIE = 'PENDING_GET_TYPE_MOVIE';
export const GET_TYPE_MOVIE_FAILED = 'GET_TYPE_MOVIE_FAILED';
export const GET_TYPE_MOVIE_SUCCESSFULLY = 'GET_TYPE_MOVIE_SUCCESSFULLY';
