export const PENDING_LOGIN = 'PENDING_LOGIN';
export const LOGIN_SUCCESSFULLY = 'LOGIN_SUCCESSFULLY';
export const LOGIN_FAILED = 'LOGIN_FAILED';
export const LOGOUT_SUCCESSFULLY = 'LOGOUT_SUCCESSFULLY';
